apiVersion: v1
kind: Secret
metadata:
  name: soda-service-secrets
  namespace: nominomi
type: Opaque
stringData:
  # Environment setting
  APP_ENVIRONMENT: "local"

  # Database configuration
  # Connecting to the Docker Compose Postgres from K8s
  # Use host.docker.internal for Docker Desktop / Minikube
  APP_DATABASE_POSTGRES_HOST: "host.docker.internal"
  APP_DATABASE_POSTGRES_PORT: "5435"
  APP_DATABASE_POSTGRES_USER: "postgres"
  APP_DATABASE_POSTGRES_PASSWORD: "password"
  APP_DATABASE_POSTGRES_NAME: "soda_interview_db"
